# AUTHOR KEYS
AUTHOR_USERNAME = "AUTHOR_USERNAME"
AUTHOR_KARMA = "AUTHOR_KARMA"
AUTHOR_ACCOUNT_AGE = "AUTHOR_ACCOUNT_AGE"

# POST KEYS
POST_ID = "POST_ID"
POST_TITLE = "POST_TITLE"
POST_PERMALINK = "POST_PERMALINK"
POST_URL = "POST_URL"
POST_SCORE = "POST_SCORE"
POST_NUM_COMMENTS = "POST_NUM_COMMENTS"
POST_CREATED_TIMESTAMP = "POST_CREATED_TIMESTAMP"
POST_SUBREDDIT = "POST_SUBREDDIT"
POST_UPVOTE_RATIO = "POST_UPVOTE_RATIO"
POST_TEXT_CONTENT = "POST_TEXT_CONTENT"
POST_TYPE = "POST_TYPE"

# COMMENT KEYS
COMMENT_ID = "COMMENT_ID"
COMMENT_TEXT_CONTENT = "COMMENT_TEXT_CONTENT"
COMMENT_SCORE = "COMMENT_SCORE"
COMMENT_DEPTH = "COMMENT_DEPTH"
COMMENT_CREATED_TIMESTAMP = "COMMENT_CREATED_TIMESTAMP"
COMMENT_PARENT_ID = "COMMENT_PARENT_ID"
